/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "primary-fixed-dim": "#b4c5ff",
              "outline": "#8d90a0",
              "surface-container-high": "#282a32",
              "error-container": "#93000a",
              "surface-bright": "#373942",
              "primary": "#b4c5ff",
              "surface-container-lowest": "#0c0e16",
              "on-secondary": "#003640",
              "primary-fixed": "#dbe1ff",
              "on-primary": "#002a78",
              "tertiary": "#d2bbff",
              "on-primary-fixed-variant": "#003ea8",
              "error": "#ffb4ab",
              "inverse-on-surface": "#2e3039",
              "on-primary-fixed": "#00174b",
              "secondary": "#4cd7f6",
              "on-secondary-container": "#00424e",
              "tertiary-container": "#8343f4",
              "tertiary-fixed-dim": "#d2bbff",
              "on-error-container": "#ffdad6",
              "on-surface": "#e1e2ed",
              "inverse-primary": "#0053db",
              "surface-variant": "#32343d",
              "on-primary-container": "#eeefff",
              "surface-container": "#1d1f27",
              "on-error": "#690005",
              "on-tertiary": "#3f008e",
              "on-tertiary-fixed": "#25005a",
              "secondary-container": "#03b5d3",
              "outline-variant": "#434655",
              "surface": "#11131b",
              "on-background": "#e1e2ed",
              "surface-container-highest": "#32343d",
              "secondary-fixed-dim": "#4cd7f6",
              "on-secondary-fixed": "#001f26",
              "secondary-fixed": "#acedff",
              "surface-tint": "#b4c5ff",
              "on-tertiary-container": "#f7edff",
              "primary-container": "#2563eb",
              "surface-container-low": "#191b23",
              "on-surface-variant": "#c3c6d7",
              "inverse-surface": "#e1e2ed",
              "on-secondary-fixed-variant": "#004e5c",
              "surface-dim": "#11131b",
              "on-tertiary-fixed-variant": "#5a00c6",
              "tertiary-fixed": "#eaddff",
              "background": "#11131b"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "fontFamily": {
              "headline-md": ["Geist"],
              "headline-lg": ["Geist"],
              "label-md": ["Geist"],
              "headline-xl": ["Geist"],
              "body-sm": ["Inter"],
              "body-lg": ["Inter"],
              "body-md": ["Inter"],
              "label-sm": ["Geist"]
      },
      "fontSize": {
              "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
              "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
              "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.02em", "fontWeight": "500"}],
              "headline-xl": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
              "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
              "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
              "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
