// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"
	"time"
)

const getLastAuditLog = `-- name: GetLastAuditLog :one
SELECT id, ts, agent_id, action, resource, decision, spend_delta, latency_ms, reason, prev_hash, entry_hash
FROM audit_log
ORDER BY id DESC
LIMIT 1
`

func (q *Queries) GetLastAuditLog(ctx context.Context) (AuditLog, error) {
	row := q.db.QueryRow(ctx, getLastAuditLog)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.Ts,
		&i.AgentID,
		&i.Action,
		&i.Resource,
		&i.Decision,
		&i.SpendDelta,
		&i.LatencyMs,
		&i.Reason,
		&i.PrevHash,
		&i.EntryHash,
	)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_log (
    ts, agent_id, action, resource, decision, spend_delta, latency_ms, reason, prev_hash, entry_hash
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
`

type InsertAuditLogParams struct {
	Ts         time.Time `json:"ts"`
	AgentID    string    `json:"agent_id"`
	Action     string    `json:"action"`
	Resource   string    `json:"resource"`
	Decision   string    `json:"decision"`
	SpendDelta int64     `json:"spend_delta"`
	LatencyMs  float64   `json:"latency_ms"`
	Reason     string    `json:"reason"`
	PrevHash   string    `json:"prev_hash"`
	EntryHash  string    `json:"entry_hash"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.Ts,
		arg.AgentID,
		arg.Action,
		arg.Resource,
		arg.Decision,
		arg.SpendDelta,
		arg.LatencyMs,
		arg.Reason,
		arg.PrevHash,
		arg.EntryHash,
	)
	return err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, ts, agent_id, action, resource, decision, spend_delta, latency_ms, reason, prev_hash, entry_hash
FROM audit_log
ORDER BY id ASC
`

func (q *Queries) ListAuditLogs(ctx context.Context) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.AgentID,
			&i.Action,
			&i.Resource,
			&i.Decision,
			&i.SpendDelta,
			&i.LatencyMs,
			&i.Reason,
			&i.PrevHash,
			&i.EntryHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
