// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type AgentInstance struct {
	AgentID   string      `json:"agent_id"`
	ProfileID pgtype.Text `json:"profile_id"`
	Status    string      `json:"status"`
	CreatedAt time.Time   `json:"created_at"`
}

type AgentProfile struct {
	ProfileID           string      `json:"profile_id"`
	ProfileName         string      `json:"profile_name"`
	Description         pgtype.Text `json:"description"`
	AllowedTools        []string    `json:"allowed_tools"`
	HourlySpendCapCents pgtype.Int8 `json:"hourly_spend_cap_cents"`
	CreatedAt           time.Time   `json:"created_at"`
}

type AuditLog struct {
	ID         int64     `json:"id"`
	Ts         time.Time `json:"ts"`
	AgentID    string    `json:"agent_id"`
	Action     string    `json:"action"`
	Resource   string    `json:"resource"`
	Decision   string    `json:"decision"`
	SpendDelta int64     `json:"spend_delta"`
	LatencyMs  float64   `json:"latency_ms"`
	Reason     string    `json:"reason"`
	PrevHash   string    `json:"prev_hash"`
	EntryHash  string    `json:"entry_hash"`
}

type Policy struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	Version   int32     `json:"version"`
	Source    string    `json:"source"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
