// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: policies.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActivePolicyFingerprint = `-- name: GetActivePolicyFingerprint :one
SELECT
    COUNT(*)::bigint AS policy_count,
    COALESCE(MAX(version), 0)::bigint AS max_version
FROM
    policies
WHERE
    status = 'active'
`

type GetActivePolicyFingerprintRow struct {
	PolicyCount int64 `json:"policy_count"`
	MaxVersion  int64 `json:"max_version"`
}

// Cheap fingerprint of the active policy set. Returns the count and max
// version across active policies. Used by the poller to skip recompiling when
// nothing changed. Count is included so that deleting a non-max-version policy
// (which leaves MAX(version) unchanged) is still detected.
func (q *Queries) GetActivePolicyFingerprint(ctx context.Context) (GetActivePolicyFingerprintRow, error) {
	row := q.db.QueryRow(ctx, getActivePolicyFingerprint)
	var i GetActivePolicyFingerprintRow
	err := row.Scan(&i.PolicyCount, &i.MaxVersion)
	return i, err
}

const listActivePolicies = `-- name: ListActivePolicies :many
SELECT
    rego_source,
    version
FROM
    policies
WHERE
    status = 'active'
ORDER BY
    id ASC
`

type ListActivePoliciesRow struct {
	RegoSource pgtype.Text `json:"rego_source"`
	Version    int32       `json:"version"`
}

func (q *Queries) ListActivePolicies(ctx context.Context) ([]ListActivePoliciesRow, error) {
	rows, err := q.db.Query(ctx, listActivePolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivePoliciesRow{}
	for rows.Next() {
		var i ListActivePoliciesRow
		if err := rows.Scan(&i.RegoSource, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
