// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: policies.sql

package db

import (
	"context"
)

const getPolicyByName = `-- name: GetPolicyByName :one
SELECT id, name, version, source, created_at, updated_at
FROM policies
WHERE name = $1
`

func (q *Queries) GetPolicyByName(ctx context.Context, name string) (Policy, error) {
	row := q.db.QueryRow(ctx, getPolicyByName, name)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPolicy = `-- name: UpsertPolicy :exec
INSERT INTO policies (name, version, source, updated_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (name) DO UPDATE SET
    version = EXCLUDED.version,
    source = EXCLUDED.source,
    updated_at = NOW()
`

type UpsertPolicyParams struct {
	Name    string `json:"name"`
	Version int32  `json:"version"`
	Source  string `json:"source"`
}

func (q *Queries) UpsertPolicy(ctx context.Context, arg UpsertPolicyParams) error {
	_, err := q.db.Exec(ctx, upsertPolicy, arg.Name, arg.Version, arg.Source)
	return err
}
