// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: policies.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listActivePolicies = `-- name: ListActivePolicies :many
SELECT rego_source, version FROM policies WHERE status = 'active' ORDER BY id ASC
`

type ListActivePoliciesRow struct {
	RegoSource pgtype.Text `json:"rego_source"`
	Version    int32       `json:"version"`
}

func (q *Queries) ListActivePolicies(ctx context.Context) ([]ListActivePoliciesRow, error) {
	rows, err := q.db.Query(ctx, listActivePolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivePoliciesRow{}
	for rows.Next() {
		var i ListActivePoliciesRow
		if err := rows.Scan(&i.RegoSource, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
