// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profiles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAgentPermissions = `-- name: GetAgentPermissions :one
SELECT i.status, COALESCE(p.allowed_tools, '{}')::text[] AS allowed_tools
FROM agent_instances i
LEFT JOIN agent_profiles p ON i.profile_id = p.profile_id
WHERE i.agent_id = $1
`

type GetAgentPermissionsRow struct {
	Status       string   `json:"status"`
	AllowedTools []string `json:"allowed_tools"`
}

func (q *Queries) GetAgentPermissions(ctx context.Context, agentID string) (GetAgentPermissionsRow, error) {
	row := q.db.QueryRow(ctx, getAgentPermissions, agentID)
	var i GetAgentPermissionsRow
	err := row.Scan(&i.Status, &i.AllowedTools)
	return i, err
}

const listAgentProfiles = `-- name: ListAgentProfiles :many
SELECT profile_id, profile_name, COALESCE(description, '')::text AS description, allowed_tools, COALESCE(hourly_spend_cap_cents, 0)::bigint AS hourly_spend_cap_cents
FROM agent_profiles
ORDER BY profile_id ASC
`

type ListAgentProfilesRow struct {
	ProfileID           string   `json:"profile_id"`
	ProfileName         string   `json:"profile_name"`
	Description         string   `json:"description"`
	AllowedTools        []string `json:"allowed_tools"`
	HourlySpendCapCents int64    `json:"hourly_spend_cap_cents"`
}

func (q *Queries) ListAgentProfiles(ctx context.Context) ([]ListAgentProfilesRow, error) {
	rows, err := q.db.Query(ctx, listAgentProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAgentProfilesRow
	for rows.Next() {
		var i ListAgentProfilesRow
		if err := rows.Scan(
			&i.ProfileID,
			&i.ProfileName,
			&i.Description,
			&i.AllowedTools,
			&i.HourlySpendCapCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAgentInstance = `-- name: UpsertAgentInstance :exec
INSERT INTO agent_instances (agent_id, profile_id, status)
VALUES ($1, $2, $3)
ON CONFLICT (agent_id) DO UPDATE SET
    profile_id = EXCLUDED.profile_id,
    status = EXCLUDED.status
`

type UpsertAgentInstanceParams struct {
	AgentID   string      `json:"agent_id"`
	ProfileID pgtype.Text `json:"profile_id"`
	Status    string      `json:"status"`
}

func (q *Queries) UpsertAgentInstance(ctx context.Context, arg UpsertAgentInstanceParams) error {
	_, err := q.db.Exec(ctx, upsertAgentInstance, arg.AgentID, arg.ProfileID, arg.Status)
	return err
}

const upsertAgentProfile = `-- name: UpsertAgentProfile :exec
INSERT INTO agent_profiles (profile_id, profile_name, description, allowed_tools, hourly_spend_cap_cents)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (profile_id) DO UPDATE SET
    profile_name = EXCLUDED.profile_name,
    description = EXCLUDED.description,
    allowed_tools = EXCLUDED.allowed_tools,
    hourly_spend_cap_cents = EXCLUDED.hourly_spend_cap_cents
`

type UpsertAgentProfileParams struct {
	ProfileID           string      `json:"profile_id"`
	ProfileName         string      `json:"profile_name"`
	Description         pgtype.Text `json:"description"`
	AllowedTools        []string    `json:"allowed_tools"`
	HourlySpendCapCents pgtype.Int8 `json:"hourly_spend_cap_cents"`
}

func (q *Queries) UpsertAgentProfile(ctx context.Context, arg UpsertAgentProfileParams) error {
	_, err := q.db.Exec(ctx, upsertAgentProfile,
		arg.ProfileID,
		arg.ProfileName,
		arg.Description,
		arg.AllowedTools,
		arg.HourlySpendCapCents,
	)
	return err
}
